import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  useAddress,
  useDisconnect,
  useSigner,
  useMetamask,
} from "@thirdweb-dev/react";

import { Button, Center, Input, useToast } from "@chakra-ui/react";
import { BigNumber } from "ethers";
import { IoLogoGithub } from "react-icons/io";
import { disconnect } from "process";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const toast = useToast();
  const signer = useSigner();

  // get a function to connect to a particular wallet
  // options: useMetamask() - useCoinbase() - useWalletConnect()
  const connectWithMetamask = useMetamask();
  const disconnectMetamask = useDisconnect();
  // once connected, you can get the connected wallet information from anywhere (address, signer)
  const address = useAddress();

  function sendTx() {
    toast({ title: "Sending transaction..." });
    signer
      ?.sendTransaction({
        to: "0x0000000000000000000000000000000000000000",
        value: BigNumber.from(0),
      })
      .then(() => {
        toast({
          title: "Transaction sent!",
          status: "success",
        });
      })
      .catch((error) => {
        console.error("failed to send transaction", error);
        toast({
          title: "Failed to send transaction",
          description: error.message,
          status: "error",
        });
      });
  }

  function signMsg() {
    toast({ title: "Signing message", status: "info", duration: 5000 });
    signer?.signMessage("this is a test message!").then(() => {
      toast({ title: "Message signed", status: "success", duration: 5000 });
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Thirdweb App</title>
        <meta name="description" content="Generated by create-thirdweb-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://thirdweb.com">thirdweb</a> NFT starter
        </h1>
        <br />
        <p className={styles.description}>
          This is a NextJS app initialises barebones react sdk{" "}
          <a href="https://npmjs.com/package/@3rdweb/react">
            thirdweb react SDK
          </a>{" "}
          with metamask connect.
          <br />
          Get started by reading <code className={styles.code}>
            readme.md
          </code>{" "}
          or editing <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div>
          {address ? (
            <>
              <Center>
                <Button onClick={disconnectMetamask}>
                  Disconnect {address}
                </Button>
              </Center>
              <div className={styles.grid}>
                <div className={styles.card}>
                  <h2>Send Transaction</h2>
                  <p>Send money to an address from connected wallet. </p>
                  <Button onClick={sendTx}>Send Transaction</Button>
                </div>
                <div className={styles.card}>
                  <h2>Sign Message </h2>
                  <p>Sign a message with public keys of connected wallet </p>
                  <Button onClick={signMsg}>Sign Message</Button>
                </div>
              </div>
            </>
          ) : (
            <Center>
              <Button onClick={connectWithMetamask}>
                Connect Metamask Wallet
              </Button>
            </Center>
          )}
          <div className={styles.grid}>
            <a
              href="https://typescript-sdk.thirdweb.com"
              className={styles.card}
            >
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about thirdweb features and API.</p>
            </a>
            <a href="https://portal.thirdweb.com" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Thirdweb modules in the thirdweb portal!</p>
            </a>
            <a
              href="https://github.com/thirdweb-dev/create-thirdweb-app/tree/main/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example thirdweb projects.</p>
            </a>
            <a href="https://thirdweb.com" className={styles.card}>
              <h2>Dashboard &rarr;</h2>
              <p>Interact with and manage thirdweb modules without code</p>
            </a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://thirdweb.com?utm_source=create-thirdweb-app&utm_medium=default-template&utm_campaign=create-thirdweb-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/thirdweb.svg"
              alt="Thirdweb Logo"
              width={29}
              height={16}
            />
          </span>
        </a>
        <a href="https://github.com/thirdweb-dev">
          <IoLogoGithub width={50} />
        </a>
      </footer>
    </div>
  );
};

export default Home;
